import type { ProofRule } from '../proofread-types';

const WHY = {
  i: {
    en: 'Bangla Academy: non-tatsama / modern words use short ই (ি).',
    bn: 'বাংলা একাডেমি: অতৎসম ও আধুনিক শব্দে হ্রস্ব ই-কার (ি) হবে।',
  },
  u: {
    en: 'Bangla Academy: this word uses short উ (ু), not long ঊ.',
    bn: 'বাংলা একাডেমি: এই শব্দে হ্রস্ব উ-কার (ু) প্রমিত।',
  },
  uu: {
    en: 'Standard spelling uses long ঊ (ূ) here.',
    bn: 'এই স্থানে দীর্ঘ ঊ-কার (ূ) প্রমিত।',
  },
  n: {
    en: 'Tatsama orthography: use মূর্ধন্য ণ / ষ where required.',
    bn: 'তৎসম বানানে প্রয়োজনীয় স্থানে মূর্ধন্য ণ বা ষ হবে।',
  },
  academy: {
    en: 'Bangla Academy standard spelling.',
    bn: 'বাংলা একাডেমি প্রমিত বানান।',
  },
  sandhi: {
    en: 'Correct sandhi / visarga form.',
    bn: 'সন্ধি বা বিসর্গের শুদ্ধ রূপ।',
  },
  redundancy: {
    en: 'Redundant suffix or double plural.',
    bn: 'বাহুল্য দোষ বা দ্বৈত বহুবচন।',
  },
  conjunct: {
    en: 'Standard conjunct / ব-ফলা / য-ফলা form.',
    bn: 'প্রমিত যুক্তবর্ণ, ব-ফলা বা য-ফলা।',
  },
  en: {
    en: 'Standard English spelling.',
    bn: 'ইংরেজি সঠিক বানান।',
  },
} as const;

function r(
  id: string,
  from: string,
  to: string,
  why: keyof typeof WHY | { en: string; bn: string },
  kind: ProofRule['kind'] = 'spelling',
  extra?: Partial<ProofRule>
): ProofRule {
  return {
    id,
    lang: extra?.lang ?? 'bn',
    from,
    to,
    why: typeof why === 'string' ? WHY[why] : why,
    kind,
    optional: extra?.optional,
  };
}

/** High-precision Academy / editorial pairs. Pattern rules cover many more forms. */
export const BENGALI_RULES: ProofRule[] = [
  r('bn_sp_bideshi', 'বিদেশী', 'বিদেশি', 'i'),
  r('bn_sp_sarkari', 'সরকারী', 'সরকারি', 'i'),
  r('bn_sp_jaruri', 'জরুরী', 'জরুরি', 'i'),
  r('bn_sp_shreni', 'শ্রেণী', 'শ্রেণি', 'i'),
  r('bn_sp_pakhi', 'পাখী', 'পাখি', 'i'),
  r('bn_sp_bari', 'বাড়ী', 'বাড়ি', 'i'),
  r('bn_sp_gari', 'গাড়ী', 'গাড়ি', 'i'),
  r('bn_sp_dabi', 'দাবী', 'দাবি', 'i'),
  r('bn_sp_tarikh', 'তারীখ', 'তারিখ', 'i'),
  r('bn_sp_chuti', 'ছুটী', 'ছুটি', 'i'),
  r('bn_sp_shroddhanjali', 'শ্রদ্ধাঞ্জলী', 'শ্রদ্ধাঞ্জলি', 'i'),
  r('bn_sp_gitanjali', 'গীতাঞ্জলী', 'গীতাঞ্জলি', 'i'),
  r('bn_sp_suchipatra', 'সূচীপত্র', 'সূচিপত্র', 'i'),
  r('bn_sp_january', 'জানুয়ারী', 'জানুয়ারি', 'i'),
  r('bn_sp_february', 'ফেব্রুয়ারী', 'ফেব্রুয়ারি', 'i'),
  r('bn_sp_protijogita', 'প্রতিযোগীতা', 'প্রতিযোগিতা', 'i'),
  r('bn_sp_sohojogita', 'সহযোগীতা', 'সহযোগিতা', 'i'),
  r('bn_sp_upojogita', 'উপযোগীতা', 'উপযোগিতা', 'i'),
  r('bn_sp_shashuri', 'শাশুড়ী', 'শাশুড়ি', 'i'),
  r('bn_sp_nani', 'নানী', 'নানি', 'i'),
  r('bn_sp_dadi', 'দাদী', 'দাদি', 'i'),
  r('bn_sp_chachi', 'চাচী', 'চাচি', 'i'),
  r('bn_sp_chakuri', 'চাকুরী', 'চাকরি', 'i'),
  r('bn_sp_torkari', 'তরকারী', 'তরকারি', 'i'),
  r('bn_sp_mati', 'মাটী', 'মাটি', 'i'),
  r('bn_sp_jomi', 'জমী', 'জমি', 'i'),
  r('bn_sp_khushi', 'খুশী', 'খুশি', 'i'),
  r('bn_sp_beshi', 'বেশী', 'বেশি', 'i'),
  r('bn_sp_bashi', 'বাশী', 'বাসি', 'i'),
  r('bn_sp_ingreji', 'ইংরেজী', 'ইংরেজি', 'i'),
  r('bn_sp_arbi', 'আরবী', 'আরবি', 'i'),
  r('bn_sp_hijri', 'হিজরী', 'হিজরি', 'i'),
  r('bn_sp_japani', 'জাপানী', 'জাপানি', 'i'),
  r('bn_sp_rupali', 'রূপালী', 'রূপালি', 'i'),
  r('bn_sp_sonali', 'সোনালী', 'সোনালি', 'i'),
  r('bn_sp_hati', 'হাতী', 'হাতি', 'i'),
  r('bn_sp_dari', 'দাড়ী', 'দাড়ি', 'i'),
  r('bn_sp_churi', 'চোরী', 'চুরি', 'i'),
  r('bn_sp_bhari', 'ভারী', 'ভারি', 'i'),
  r('bn_sp_durabostha', 'দূরবস্থা', 'দুরবস্থা', 'u'),
  r('bn_sp_duranto', 'দূরন্ত', 'দুরন্ত', 'u'),
  r('bn_sp_durniti', 'দূর্নীতি', 'দুর্নীতি', 'u'),
  r('bn_sp_durghotona', 'দূর্ঘটনা', 'দুর্ঘটনা', 'u'),
  r('bn_sp_durjog', 'দূর্যোগ', 'দুর্যোগ', 'u'),
  r('bn_sp_vuktovogi', 'ভূক্তভোগী', 'ভুক্তভোগী', 'u'),
  r('bn_sp_muhurto', 'মুহুর্ত', 'মুহূর্ত', 'uu'),
  r('bn_sp_onubad', 'অনূবাদ', 'অনুবাদ', 'u'),
  r('bn_sp_onudito', 'অনুদিত', 'অনূদিত', 'uu'),
  r('bn_sp_mullayon', 'মুল্যায়ন', 'মূল্যায়ন', 'uu'),
  r('bn_sp_bhumikomp', 'ভুমিকম্প', 'ভূমিকম্প', 'uu'),

  r('bn_sp_porishkar', 'পরিস্কার', 'পরিষ্কার', 'n'),
  r('bn_sp_abishkar', 'আবিস্কার', 'আবিষ্কার', 'n'),
  r('bn_sp_purashkar', 'পুরষ্কার', 'পুরস্কার', 'n'),
  r('bn_sp_tiroshkar', 'তিরষ্কার', 'তিরস্কার', 'n'),
  r('bn_sp_akoshmik', 'আকষ্মিক', 'আকস্মিক', 'n'),
  r('bn_sp_dharona', 'ধারনা', 'ধারণা', 'n'),
  r('bn_sp_nirnoy', 'নির্নয়', 'নির্ণয়', 'n'),
  r('bn_sp_nimontron', 'নিমন্ত্রন', 'নিমন্ত্রণ', 'n'),
  r('bn_sp_bornona', 'বর্ননা', 'বর্ণনা', 'n'),
  r('bn_sp_prani', 'প্রানী', 'প্রাণী', 'n'),
  r('bn_sp_pran', 'প্রান', 'প্রাণ', 'n'),
  r('bn_sp_bani', 'বানী', 'বাণী', 'n'),
  r('bn_sp_smaronio', 'স্মরনীয়', 'স্মরণীয়', 'n'),
  r('bn_sp_dandabidhi', 'দন্ডবিধি', 'দণ্ডবিধি', 'n'),
  r('bn_sp_porinoti', 'পরিনতি', 'পরিণতি', 'n'),
  r('bn_sp_nirman', 'নির্মান', 'নির্মাণ', 'n'),

  r('bn_sp_aschorjo', 'আশ্চর্য্য', 'আশ্চর্য', 'conjunct'),
  r('bn_sp_onibarjo', 'অনিবার্য্য', 'অনিবার্য', 'conjunct'),
  r('bn_sp_akanhkha', 'আকাংখা', 'আকাঙ্ক্ষা', 'conjunct'),
  r('bn_sp_santwona', 'সান্তনা', 'সান্ত্বনা', 'conjunct'),
  r('bn_sp_ucchwas', 'উচ্ছাস', 'উচ্ছ্বাস', 'conjunct'),
  r('bn_sp_ujjwol', 'উজ্জল', 'উজ্জ্বল', 'conjunct'),
  r('bn_sp_shoshur', 'শশুর', 'শ্বশুর', 'conjunct'),
  r('bn_sp_dhonobad', 'ধন্নবাদ', 'ধন্যবাদ', 'conjunct'),
  r('bn_sp_monojog', 'মনযোগ', 'মনোযোগ', 'sandhi'),
  r('bn_sp_itopurbey', 'ইতোপূর্বে', 'ইতঃপূর্বে', 'sandhi'),
  r('bn_sp_swayottoshashon', 'স্বায়ত্বশাসন', 'স্বায়ত্তশাসন', 'conjunct'),
  r('bn_sp_nistobdhota', 'নিস্তব্দতা', 'নিস্তব্ধতা', 'conjunct'),
  r('bn_sp_uporokto', 'উপরোক্ত', 'উপর্যুক্ত', 'sandhi'),
  r('bn_sp_shirocched', 'শিরচ্ছেদ', 'শিরশ্ছেদ', 'sandhi'),
  r('bn_sp_monokosto', 'মনকষ্ট', 'মনঃকষ্ট', 'sandhi'),
  r('bn_sp_muhurmuhu', 'মুহূর্মুহু', 'মুহুর্মুহু', 'u'),

  r('bn_sp_rongin', 'রঙ্গীন', 'রঙিন', 'academy'),
  r('bn_sp_bhanga', 'ভাঙ্গা', 'ভাঙা', 'academy'),
  r('bn_sp_angul', 'আঙ্গুল', 'আঙুল', 'academy'),
  r('bn_sp_tangano', 'টাঙ্গানো', 'টাঙানো', 'academy'),
  r('bn_sp_onko', 'অংক', 'অঙ্ক', 'academy'),
  r('bn_sp_atonko', 'আতংক', 'আতঙ্ক', 'academy'),
  r('bn_sp_shonko', 'শংকিত', 'শঙ্কিত', 'academy'),

  r('bn_sp_karjoto', 'কার্যতঃ', 'কার্যত', 'sandhi'),
  r('bn_sp_foloto', 'ফলতঃ', 'ফলত', 'sandhi'),
  r('bn_sp_bostuto', 'বস্তুতঃ', 'বস্তুত', 'sandhi'),
  r('bn_sp_prodhanoto', 'প্রধানতঃ', 'প্রধানত', 'sandhi'),
  r('bn_sp_muloto', 'মূলতঃ', 'মূলত', 'sandhi'),
  r('bn_sp_prayosho', 'প্রায়শঃ', 'প্রায়শ', 'sandhi'),
  r('bn_sp_kromosho', 'ক্রমশঃ', 'ক্রমশ', 'sandhi'),
  r('bn_sp_sadharanoto', 'সাধারণতঃ', 'সাধারণত', 'sandhi'),
  r('bn_sp_antoto', 'অন্ততঃ', 'অন্তত', 'sandhi'),

  r('bn_sp_shoporibare', 'স্বপরিবারে', 'সপরিবারে', 'academy'),
  r('bn_sp_lojjashkor', 'লজ্জাস্কর', 'লজ্জাকর', 'academy'),
  r('bn_sp_montritwo', 'মন্ত্রীত্ব', 'মন্ত্রিত্ব', 'i'),
  r('bn_sp_dayittwo', 'দায়ীত্ব', 'দায়িত্ব', 'i'),
  r('bn_sp_ainjibi', 'আইনজীবি', 'আইনজীবী', {
    en: 'The suffix -জীবী takes long ী.',
    bn: '"-জীবী" প্রত্যয়ে দীর্ঘ ঈ-কার হবে।',
  }),
  r('bn_sp_buddhijibi', 'বুদ্ধিজীবি', 'বুদ্ধিজীবী', {
    en: 'The suffix -জীবী takes long ী.',
    bn: 'শুদ্ধ বানান "বুদ্ধিজীবী"।',
  }),
  r('bn_sp_chakurijibi', 'চাকুরিজীবি', 'চাকরিজীবী', 'academy'),
  r('bn_sp_peshajibi', 'পেশাজীবি', 'পেশাজীবী', {
    en: 'The suffix -জীবী takes long ী.',
    bn: 'শুদ্ধ বানান "পেশাজীবী"।',
  }),
  r('bn_sp_oporanhno', 'অপরাহ্ন', 'অপরাহ্ণ', 'n'),
  r('bn_sp_moddhanho', 'মধাহ্ন', 'মধ্যাহ্ন', 'academy'),
  r('bn_sp_moddhanho_2', 'মধ্যহ্ন', 'মধ্যাহ্ন', 'academy'),
  r('bn_sp_purbanho', 'পূর্বাহ্ন', 'পূর্বাহ্ণ', 'n'),

  r('bn_sp_onushthan', 'অনুষ্টান', 'অনুষ্ঠান', 'conjunct'),
  r('bn_sp_chikitsha', 'চিকিত্সা', 'চিকিৎসা', 'conjunct'),
  r('bn_sp_projojon', 'প্রয়জন', 'প্রয়োজন', 'academy'),
  r('bn_sp_poribesh', 'পরিবেষ', 'পরিবেশ', 'academy'),
  r('bn_sp_obhijog', 'অভিজোগ', 'অভিযোগ', 'academy'),
  r('bn_sp_onumodon', 'অনুমদন', 'অনুমোদন', 'academy'),
  r('bn_sp_unnati', 'উনতি', 'উন্নতি', 'academy'),
  r('bn_sp_unnoyon', 'উনয়ন', 'উন্নয়ন', 'academy'),
  r('bn_sp_kollyan', 'কল্যান', 'কল্যাণ', 'n'),
  r('bn_sp_gobeshona', 'গবেষনা', 'গবেষণা', 'n'),
  r('bn_sp_byabohar', 'বেবহার', 'ব্যবহার', 'academy'),
  r('bn_sp_protibesh', 'প্রতিবেষী', 'প্রতিবেশী', 'academy'),
  r('bn_sp_uthan', 'উঠান', 'উঠোন', 'academy'),
  r('bn_sp_onubhuti', 'অনুভুতি', 'অনুভূতি', 'uu'),
  r('bn_sp_obhijog2', 'অভিজোগ্য', 'অভিযোগ', 'academy'),
  r('bn_sp_protibesh2', 'প্রতিবেশি', 'প্রতিবেশী', {
    en: 'The word প্রতিবেশী takes long ী.',
    bn: 'শুদ্ধ বানান "প্রতিবেশী" (দীর্ঘ ঈ-কার)।',
  }),
  r('bn_sp_nari', 'নারি', 'নারী', {
    en: 'স্ত্রীবাচক "নারী" takes long ী.',
    bn: 'স্ত্রীবাচক শব্দে দীর্ঘ ঈ-কার: "নারী"।',
  }),
  r('bn_sp_podobi', 'পদবী', 'পদবি', 'i'),
  r('bn_sp_kingbodonti', 'কিংবদন্তী', 'কিংবদন্তি', 'i'),
  r('bn_sp_dhuli', 'ধূলী', 'ধূলি', 'i'),
  r('bn_sp_ponji', 'পঞ্জী', 'পঞ্জি', 'i'),
  r('bn_sp_chitkar', 'চীৎকার', 'চিৎকার', 'i'),
  r('bn_sp_dhmoni', 'ধমনী', 'ধমনি', 'i'),
  r('bn_sp_khanjoni', 'খঞ্জনী', 'খঞ্জনি', 'i'),
  r('bn_sp_bomabaji', 'বোমাবাজী', 'বোমাবাজি', 'i'),

  r('bn_rd_sob_pakhira', 'সব পাখিরা', 'সব পাখি', 'redundancy', 'grammar'),
  r('bn_rd_sokol_shodoshyogon', 'সকল সদস্যগণ', 'সকল সদস্য', 'redundancy', 'grammar'),
  r('bn_rd_sokol_manushera', 'সকল মানুষেরা', 'সকল মানুষ', 'redundancy', 'grammar'),
  r('bn_rd_kebolmatro', 'কেবলমাত্র', 'কেবল', 'redundancy', 'grammar'),
  r('bn_rd_shudhumatro', 'শুধুমাত্র', 'শুধু', 'redundancy', 'grammar'),
  r('bn_rd_oshrujol', 'অশ্রুজল', 'অশ্রু', 'redundancy', 'grammar'),
  r('bn_rd_utkorshota', 'উৎকর্ষতা', 'উৎকর্ষ', 'redundancy', 'grammar'),
  r('bn_rd_daridryota', 'দারিদ্র্যতা', 'দারিদ্র্য', 'redundancy', 'grammar'),
  r('bn_rd_sokhyota', 'সখ্যতা', 'সখ্য', 'redundancy', 'grammar'),
  r('bn_rd_oikyota', 'ঐক্যতা', 'ঐক্য', 'redundancy', 'grammar'),
  r('bn_rd_dainyota', 'দৈন্যতা', 'দৈন্য', 'redundancy', 'grammar'),
  r('bn_rd_soujonyota', 'সৌজন্যতা', 'সৌজন্য', 'redundancy', 'grammar'),
  r('bn_rd_gotokalke', 'গতকালকে', 'গতকাল', 'redundancy', 'grammar'),
  r('bn_rd_onekhon_jabat', 'অনেকক্ষণ যাবত', 'অনেকক্ষণ ধরে', 'redundancy', 'grammar'),
  r('bn_rd_sokol_chhatrogon', 'সকল ছাত্রগণ', 'সকল ছাত্র', 'redundancy', 'grammar'),
  r('bn_rd_somosto_lokera', 'সমস্ত লোকেরা', 'সমস্ত লোক', 'redundancy', 'grammar'),

  r('bn_gr_jaiteseelo', 'যাইতেছিল', 'যাচ্ছিল', {
    en: 'Sadhu verb. In modern standard prose, use যাচ্ছিল.',
    bn: 'সাধু রূপ। প্রমিত চলিত গদ্যে "যাচ্ছিল" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_koritechhilo', 'করিতেছিল', 'করছিল', {
    en: 'Sadhu verb. In modern standard prose, use করছিল.',
    bn: 'সাধু রূপ। চলিত গদ্যে "করছিল" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_boliachhilen', 'বলিয়াছিলেন', 'বলেছিলেন', {
    en: 'Sadhu verb. In modern standard prose, use বলেছিলেন.',
    bn: 'সাধু রূপ। চলিত ভাষায় "বলেছিলেন" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_tahake', 'তাহাকে', 'তাকে', {
    en: 'Sadhu pronoun. In modern prose, use তাকে.',
    bn: 'সাধু সর্বনাম। চলিত ভাষায় "তাকে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_tahader', 'তাহাদের', 'তাদের', {
    en: 'Sadhu pronoun. In modern prose, use তাদের.',
    bn: 'সাধু সর্বনাম। চলিত ভাষায় "তাদের" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_uhar', 'উহার', 'তার', {
    en: 'Sadhu pronoun. In modern prose, use তার.',
    bn: 'সাধু সর্বনাম। চলিত ভাষায় "তার" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_ihate', 'ইহাতে', 'এতে', {
    en: 'Sadhu pronoun. In modern prose, use এতে.',
    bn: 'সাধু সর্বনাম। চলিত ভাষায় "এতে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_korilo', 'করিল', 'করল', {
    en: 'Sadhu verb. In modern prose, use করল.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "করল" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_bolilo', 'বলিল', 'বলল', {
    en: 'Sadhu verb. In modern prose, use বলল.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "বলল" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_jaibe', 'যাইবে', 'যাবে', {
    en: 'Sadhu verb. In modern prose, use যাবে.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "যাবে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_koribe', 'করিবে', 'করবে', {
    en: 'Sadhu verb. In modern prose, use করবে.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "করবে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_hoitechhe', 'হইতেছে', 'হচ্ছে', {
    en: 'Sadhu verb. In modern prose, use হচ্ছে.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "হচ্ছে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),
  r('bn_gr_asitechhe', 'আসিতেছে', 'আসছে', {
    en: 'Sadhu verb. In modern prose, use আসছে.',
    bn: 'সাধু ক্রিয়া। চলিত গদ্যে "আসছে" ব্যবহার করুন।',
  }, 'grammar', { optional: true }),

  r('bn_st_korlo', 'করলো', 'করল', {
    en: 'Standard prose prefers করল. Dialogue may keep করলো.',
    bn: 'প্রমিত গদ্যে "করল" শ্রেয়। সংলাপে "করলো" রাখা যায়।',
  }, 'style', { optional: true }),
  r('bn_st_bollo', 'বললো', 'বলল', {
    en: 'Standard prose prefers বলল.',
    bn: 'প্রমিত গদ্যে "বলল" ব্যবহার করতে পারেন।',
  }, 'style', { optional: true }),
  r('bn_st_holo', 'হলো', 'হল', {
    en: 'Standard prose prefers হল.',
    bn: 'প্রমিত গদ্যে "হল" রূপটি ব্যবহৃত হয়।',
  }, 'style', { optional: true }),
  r('bn_st_gelo', 'গেলো', 'গেল', {
    en: 'Standard prose prefers গেল.',
    bn: 'প্রমিত গদ্যে "গেল" রূপটি শ্রেয়।',
  }, 'style', { optional: true }),
  r('bn_st_khelo', 'খেলো', 'খেল', {
    en: 'Standard prose prefers খেল.',
    bn: 'প্রমিত গদ্যে "খেল" রূপটি শ্রেয়।',
  }, 'style', { optional: true }),
  r('bn_st_dekhlo', 'দেখলো', 'দেখল', {
    en: 'Standard prose prefers দেখল.',
    bn: 'প্রমিত গদ্যে "দেখল" রূপটি শ্রেয়।',
  }, 'style', { optional: true }),
  r('bn_st_shunlo', 'শুনলো', 'শুনল', {
    en: 'Standard prose prefers শুনল.',
    bn: 'প্রমিত গদ্যে "শুনল" রূপটি শ্রেয়।',
  }, 'style', { optional: true }),
  r('bn_st_kenona_comma', 'কেননা,', 'কেননা', {
    en: 'A comma is usually unnecessary after কেননা.',
    bn: '"কেননা"-র পর সাধারণত কমা লাগে না।',
  }, 'punctuation'),
];

export const ENGLISH_RULES: ProofRule[] = [
  r('en_sp_teh', 'teh', 'the', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_recieve', 'recieve', 'receive', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_seperate', 'seperate', 'separate', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_definately', 'definately', 'definitely', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_occured', 'occured', 'occurred', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_accommodate', 'accomodate', 'accommodate', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_until', 'untill', 'until', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_necessary', 'neccessary', 'necessary', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_privilege', 'priviledge', 'privilege', 'en', 'spelling', { lang: 'en' }),
  r('en_sp_maintenance', 'maintainance', 'maintenance', 'en', 'spelling', { lang: 'en' }),
  r('en_gr_their_there', 'their is', 'there is', {
    en: 'Use "there is" (their is possessive).',
    bn: '"there is" ব্যবহার করুন ("their" অধিকারবাচক)।',
  }, 'grammar', { lang: 'en', optional: true }),
  r('en_gr_its_it_is', 'its a', "it's a", {
    en: 'Contraction for "it is a" needs an apostrophe.',
    bn: '"it\'s a" (it is)-এ অ্যাপোস্ট্রফি বসবে।',
  }, 'grammar', { lang: 'en', optional: true }),
  r('en_gr_loose_lose', 'loose weight', 'lose weight', {
    en: 'Use "lose" for reduction ("loose" means not tight).',
    bn: '"lose weight" হবে ("loose" মানে ঢিলেঢালা)।',
  }, 'grammar', { lang: 'en' }),
];
